In [73]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [74]:
x=pd.DataFrame({"key":range(0,5),"left_values":[10,20,30,40,50]})
x

   key  left_values
0    0           10
1    1           20
2    2           30
3    3           40
4    4           50

In [75]:
y=pd.DataFrame({"key":range(2,7),"right_val":[60,70,80,90,100]})
y

   key  right_val
0    2         60
1    3         70
2    4         80
3    5         90
4    6        100

In [76]:
z1=pd.merge(x,y,how="inner")
z1

   key  left_values  right_val
0    2           30         60
1    3           40         70
2    4           50         80

In [88]:
da=pd.read_csv("/content/u.data",sep="\t",names=["ID","B","C","D"])
da.head(5)

    ID    B  C          D
0  196  242  3  881250949
1  186  302  3  891717742
2   22  377  1  878887116
3  244   51  2  880606923
4  166  346  1  886397596

In [78]:
da.groupby("A").agg({"B":["mean","min","max"]})

              B
           mean  min   max
A
1    136.500000    1   272
2    249.500000    1   316
3    318.814815  181   355
4    291.041667   11   362
5    291.291429    1   457
..          ...  ...   ...
939  514.081633    9  1277
940  346.850467    4  1401
941  357.818182    1  1007
942  429.113924   31  1221
943  379.089286    2  1330

[943 rows x 3 columns]

In [79]:
da.groupby("B").count().mean()

A    59.453032
C    59.453032
D    59.453032
dtype: float64

In [80]:
da.isna().sum()

A    0
B    0
C    0
D    0
dtype: int64

In [81]:
da.info()
da.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   A       100000 non-null  int64
 1   B       100000 non-null  int64
 2   C       100000 non-null  int64
 3   D       100000 non-null  int64
dtypes: int64(4)
memory usage: 3.1 MB

                  A              B              C             D
count  100000.00000  100000.000000  100000.000000  1.000000e+05
mean      462.48475     425.530130       3.529860  8.835289e+08
std       266.61442     330.798356       1.125674  5.343856e+06
min         1.00000       1.000000       1.000000  8.747247e+08
25%       254.00000     175.000000       3.000000  8.794487e+08
50%       447.00000     322.000000       4.000000  8.828269e+08
75%       682.00000     631.000000       4.000000  8.882600e+08
max       943.00000    1682.000000       5.000000  8.932866e+08

In [82]:
da.mode()

     A   B  C          D
0  405  50  4  891033606

In [83]:
da.max()

A          943
B         1682
C            5
D    893286638
dtype: int64

In [84]:
da.mean()

A    4.624848e+02
B    4.255301e+02
C    3.529860e+00
D    8.835289e+08
dtype: float64

In [85]:
data=da.groupby("A").mean().sort_values(ascending=False,by="B")
data

              B         C             D
A
782  858.275862  2.788793  8.914991e+08
181  786.220690  1.491954  8.789625e+08
405  732.933514  1.834464  8.855476e+08
845  726.838710  3.129032  8.854095e+08
341  713.952381  3.809524  8.907579e+08
..          ...       ...           ...
352  209.309524  3.738095  8.842901e+08
700  193.523810  3.666667  8.844941e+08
124  190.041667  3.500000  8.903016e+08
737  188.181818  3.969697  8.843149e+08
1    136.500000  3.610294  8.773916e+08

[943 rows x 3 columns]

In [86]:
ta=pd.read_csv("/content/u.item",sep="|",encoding="Latin-1",names=["ID","movie","date","null values","link"],usecols=range(5))
ta.head(5)

,ID,movie,date,null values,link
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995)

In [90]:
new=pd.merge(da,ta)
new

,ID,B,C,D,movie,date,null values,link
0,196,242,3,881250949,Dead Poets Society (1989),01-Jan-1989,NaN,http://us.imdb.com/M/title-exact?Dead%20Poets%...
1,196,393,4,881251863,Dead Poets Society (1989),01-Jan-1989,NaN,http://us.imdb.com/M/title-exact?Dead%20Poets%...
2,196,381,4,881251728,Dead Poets Society (1989),01-Jan-1989,NaN,http://us.imdb.com/M/title-exact?Dead%20Poets%...
3,196,251,3,881251274,Dead Poets Society (1989),01-Jan-1989,NaN,http://us.imdb.com/M/title-exact?Dead%20Poets%...
4,196,655,5,881251793,Dead Poets Society (1989),01-Jan-1989,NaN,http://us.imdb.com/M/title-exact?Dead%20Poets%...
...,...,...,...,...,...,...,...,...
99995,941,919,5,875048887,With Honors (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?With%20Honors...
99996,941,273,3,875049038,With Honors (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?With%20Honors...
99997,941,1,5,875049144,With Honors (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?With%20Honors...
99998,941,294,4,875048532,With Honors (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?With%20Honors...
99999,941,1007,4,875049077,With Honors (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?With%20Honors...

In [97]:
x=pd.merge(da,ta,how="left",left_on="ID",right_on="ID")
x

,ID,B,C,D,movie,date,null values,link
0,196,242,3,881250949,Dead Poets Society (1989),01-Jan-1989,NaN,http://us.imdb.com/M/title-exact?Dead%20Poets%...
1,186,302,3,891717742,"Blues Brothers, The (1980)",01-Jan-1980,NaN,http://us.imdb.com/M/title-exact?Blues%20Broth...
2,22,377,1,878887116,Braveheart (1995),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Braveheart%20...
3,244,51,2,880606923,Smilla's Sense of Snow (1997),14-Mar-1997,NaN,http://us.imdb.com/M/title-exact?Smilla%27s%20...
4,166,346,1,886397596,Manon of the Spring (Manon des sources) (1986),01-Jan-1986,NaN,http://us.imdb.com/M/title-exact?Manon%20des%2...
...,...,...,...,...,...,...,...,...
99995,880,476,3,880175444,Soul Food (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Soul+Food+(1997)
99996,716,204,5,879795543,Home for the Holidays (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Home%20for%20...
99997,276,1090,1,874795795,Leaving Las Vegas (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Leaving%20Las...
99998,13,225,2,882399156,Mighty Aphrodite (1995),30-Oct-1995,NaN,http://us.imdb.com/M/title-exact?Mighty%20Aphr...
99999,12,203,3,879959583,"Usual Suspects, The (1995)",14-Aug-1995,NaN,http://us.imdb.com/M/title-exact?Usual%20Suspe...

In [98]:
x.head(30)

,ID,B,C,D,movie,date,null values,link
0,196,242,3,881250949,Dead Poets Society (1989),01-Jan-1989,NaN,http://us.imdb.com/M/title-exact?Dead%20Poets%...
1,186,302,3,891717742,"Blues Brothers, The (1980)",01-Jan-1980,NaN,http://us.imdb.com/M/title-exact?Blues%20Broth...
2,22,377,1,878887116,Braveheart (1995),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Braveheart%20...
3,244,51,2,880606923,Smilla's Sense of Snow (1997),14-Mar-1997,NaN,http://us.imdb.com/M/title-exact?Smilla%27s%20...
4,166,346,1,886397596,Manon of the Spring (Manon des sources) (1986),01-Jan-1986,NaN,http://us.imdb.com/M/title-exact?Manon%20des%2...
5,298,474,4,884182806,Face/Off (1997),27-Jun-1997,NaN,http://us.imdb.com/M/title-exact?Face/Off+(1997)
6,115,265,2,881171488,"Haunted World of Edward D. Wood Jr., The (1995)",26-Apr-1996,NaN,http://us.imdb.com/Title?Haunted+World+of+Edwa...
7,253,465,5,891628467,"Pillow Book, The (1995)",13-Jun-1997,NaN,http://us.imdb.com/M/title-exact?Pillow%20Book...
8,305,451,3,886324817,"Ice Storm, The (1997)",01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Ice+Storm%2C+...
9,6,86,3,883603013,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,01-Jan-1995,NaN,http://us.imdb.com/Title?Yao+a+yao+yao+dao+wai...
10,62,257,2,879372434,Stargate (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Stargate%20(1...
11,286,1014,5,879781125,"English Patient, The (1996)",15-Nov-1996,NaN,http://us.imdb.com/M/title-exact?English%20Pat...
12,200,222,5,876042340,"Shining, The (1980)",01-Jan-1980,NaN,"http://us.imdb.com/M/title-exact?Shining,%20Th..."
13,210,40,3,891035994,Indiana Jones and the Last Crusade (1989),01-Jan-1989,NaN,http://us.imdb.com/M/title-exact?Indiana%20Jon...
14,224,29,3,888104457,Ridicule (1996),27-Nov-1996,NaN,http://us.imdb.com/M/title-exact?Ridicule%20(1...
15,303,785,3,879485318,Ulee's Gold (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Ulee%27s+Gold...
16,122,387,5,879270459,"Cable Guy, The (1996)",14-Jun-1996,NaN,"http://us.imdb.com/M/title-exact?Cable%20Guy,%..."
17,194,274,2,879539794,"Sting, The (1973)",01-Jan-1973,NaN,"http://us.imdb.com/M/title-exact?Sting,%20The%..."
18,291,1042,4,874834944,Absolute Power (1997),14-Feb-1997,NaN,http://us.imdb.com/M/title-exact?Absolute%20Po...
19,234,1184,2,892079237,Jaws (1975),01-Jan-1975,NaN,http://us.imdb.com/M/title-exact?Jaws%20(1975)
20,119,392,4,886176814,Maya Lin: A Strong Clear Vision (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Maya%20Lin:%2...
21,167,486,4,892738452,Private Benjamin (1980),01-Jan-1980,NaN,http://us.imdb.com/M/title-exact?Private%20Ben...
22,299,144,4,877881320,Hoodlum (1997),22-Aug-1997,NaN,http://us.imdb.com/M/title-exact?Hoodlum+(1997)
23,291,118,2,874833878,Absolute Power (1997),14-Feb-1997,NaN,http://us.imdb.com/M/title-exact?Absolute%20Po...
24,308,1,4,887736532,FairyTale: A True Story (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Fairytale:+A+...
25,95,546,2,879196566,Aladdin (1992),01-Jan-1992,NaN,http://us.imdb.com/M/title-exact?Aladdin%20(1992)
26,38,95,5,892430094,"Net, The (1995)",01-Jan-1995,NaN,"http://us.imdb.com/M/title-exact?Net,%20The%20..."
27,102,768,2,883748450,"Aristocats, The (1970)",01-Jan-1970,NaN,"http://us.imdb.com/M/title-exact?Aristocats,%2..."
28,63,277,4,875747401,"Santa Clause, The (1994)",01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Santa%20Claus...
29,160,234,5,876861185,Glengarry Glen Ross (1992),01-Jan-1992,NaN,http://us.imdb.com/M/title-exact?Glengarry%20G...